name: lint & typescript check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./template
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm
      - run: mv _eslintrc.js .eslintrc.js && mv _prettierrc.js .prettierrc.js
      - name: Lint code
        run: npm lint